# Generated by Django 5.2.14 on 2026-05-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_overall_alter_club_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='overall',
        ),
        migrations.AlterField(
            model_name='club',
            name='budget',
            field=models.BigIntegerField(default=15000000),
        ),
    ]
