# Generated by Django 5.2.14 on 2026-05-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('season', models.IntegerField(default=2026)),
                ('current_round', models.IntegerField(default=1)),
                ('transfer_window_open', models.BooleanField(default=True)),
            ],
        ),
    ]
