# Generated by Django 5.2.14 on 2026-05-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='player',
            name='defending',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='dribbling',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='pace',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='passing',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='physical',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='shooting',
            field=models.IntegerField(default=50),
        ),
    ]
