# Generated by Django 5.2.14 on 2026-05-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_age_alter_player_defending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='value',
            field=models.IntegerField(default=1000000),
        ),
    ]
