# Generated by Django 5.2.14 on 2026-05-26 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('overall', models.IntegerField(default=75)),
                ('reputation', models.IntegerField(default=70)),
                ('budget', models.IntegerField(default=50000000)),
                ('primary_color', models.CharField(default='#ffffff', max_length=20)),
                ('secondary_color', models.CharField(default='#000000', max_length=20)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='leagues.league')),
            ],
        ),
    ]
