# Generated by Django 5.2.14 on 2026-05-27 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='overall',
        ),
        migrations.RemoveField(
            model_name='club',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='club',
            name='secondary_color',
        ),
        migrations.AlterField(
            model_name='club',
            name='budget',
            field=models.IntegerField(default=15000000),
        ),
        migrations.AlterField(
            model_name='club',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='leagues.league'),
        ),
        migrations.AlterField(
            model_name='club',
            name='reputation',
            field=models.IntegerField(default=50),
        ),
    ]
