# Generated by Django 5.2.14 on 2026-05-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_remove_club_overall_remove_club_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='overall',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='club',
            name='budget',
            field=models.BigIntegerField(default=25000000),
        ),
    ]
