# Generated by Django 5.2.14 on 2026-05-26 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=20)),
                ('nationality', models.CharField(default='Unknown', max_length=50)),
                ('position', models.CharField(default='CM', max_length=10)),
                ('overall', models.IntegerField(default=70)),
                ('potential', models.IntegerField(default=75)),
                ('pace', models.IntegerField(default=70)),
                ('shooting', models.IntegerField(default=70)),
                ('passing', models.IntegerField(default=70)),
                ('dribbling', models.IntegerField(default=70)),
                ('defending', models.IntegerField(default=70)),
                ('physical', models.IntegerField(default=70)),
                ('value', models.BigIntegerField(default=1000000)),
                ('wage', models.BigIntegerField(default=10000)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='clubs.club')),
            ],
        ),
    ]
