# Generated by Django 5.2.14 on 2026-05-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='defense',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='player',
            name='gk_diving',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='player',
            name='gk_handling',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='player',
            name='gk_kicking',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='player',
            name='gk_positioning',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='player',
            name='gk_reflexes',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='player',
            name='physical',
            field=models.IntegerField(default=60),
        ),
    ]
