# Generated by Django 5.2.14 on 2026-05-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_defense_player_gk_diving_player_gk_handling_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='defense',
        ),
        migrations.AlterField(
            model_name='player',
            name='gk_diving',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='gk_handling',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='gk_kicking',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='gk_positioning',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='gk_reflexes',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='physical',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='value',
            field=models.BigIntegerField(default=1000000),
        ),
    ]
