# Generated by Django 5.2.14 on 2026-05-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_remove_player_defense_alter_player_gk_diving_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=25),
        ),
    ]
